### PR TITLE
Convert Manual to RST

### PR DESCRIPTION
**Pull request by junghans**
Ok here how to build the new sphinx page:
```bash
git clone --recursive https://github.com/votca/votca
cd votca
git -C csg-manual checkout convert_tex_David
mkdir build
cd build
cmake -DBUILD_CSG_MANUAL=ON ..
make
make doc
firefox sphinx.html/index.html
```

### CODE REVIEW

**Comment by junghans** [comment]
Currently it has these errors:
```
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:666: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:677: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:761: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:786: WARNING: Unknown interpreted text role "raw-latex".
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:794: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:799: WARNING: Unknown interpreted text role "raw-latex".
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:806: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:818: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:823: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:828: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:858: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:884: WARNING: Unknown interpreted text role "raw-latex".
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:898: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:900: WARNING: Unknown interpreted text role "raw-latex".
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:900: WARNING: Unknown interpreted text role "raw-latex".
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:919: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:930: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:1028: WARNING: image file not readable: usage/fig/flow_boltzmann.eps
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:208: WARNING: image file not readable: fig/propane_hist2d
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:214: WARNING: image file not readable: fig/hexane2
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst:236: WARNING: image file not readable: usage/fig/flow_fmatch.eps
/__w/csg-manual/csg-manual/builddir/sphinx/VOTCA_LANGUAGE_GUIDE.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/advanced_topics.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/inputfiles.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/introduction.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/manual.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/newcommands.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/reference.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/theory.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/titlepage.rst: WARNING: document isn't included in any toctree
/__w/csg-manual/csg-manual/builddir/sphinx/usage.rst: WARNING: document isn't included in any toctree
```

I can help with the images by copying them into right places by cmake.

**Comment by marvinbernhardt** [comment]
> Ok here how to build the new sphinx page:
> 
> ```shell
> git clone --recursive https://github.com/votca/votca
> cd votca
> git -C csg-manual checkout convert_tex_David
> mkdir build
> cd build
> cmake -DBUILD_CSG_MANUAL=ON ..
> make
> make doc
> firefox sphinx.html/index.html
> ```

Following this i get 
```
$ make doc
make: *** No rule to make target 'doc'.  Stop.
```
there is only a rule called doc-csg-manual, but that does not create html files.

**Comment by junghans** [comment]
> Following this i get
> 
> ```
> $ make doc
> make: *** No rule to make target 'doc'.  Stop.
> ```

Make sure you have `sphinx-build` installed.

**Comment by junghans** [comment]
@marvinbernhardt @DRosen285 any news on this?

**Comment by marvinbernhardt** [comment]
Well I can build it now, but then I was discouraged by seeing that the errors are distributed over several repos. Might give it a go later or on the weekend.

**Comment by junghans** [comment]
> Well I can build it now, but then I was discouraged by seeing that the errors are distributed over several repos. Might give it a go later or on the weekend.

Most of the warnings are coming for the new `manual.rst` file.

I fixed some of the others in https://github.com/votca/votca/pull/519

**Comment by marvinbernhardt** [comment]
I made a first working version of the HTML Manual. But it seems I don't have write access. Can someone give it to me?

**Comment by JensWehner** [comment]
@marvinbernhardt you should have it now.

**Comment by marvinbernhardt** [comment]
Ok some notes:

- this also requires a change in votca/share/doc/index.rst:
  ```
  -   CSG-MANUAL.rst
  +   csg-manual/index.rst
  ```
- I removed all tex files and most scripts and made all figures png for now
  - if we still want to generate a pdf manual, it should be generated from the rst files, such that there is only one source.
  - the figures made by tikz should maybe generated on the fly
  - the original eps files should maybe be converted to svg
- I did not do the reference part yet
  - this will require rewriting of some scripts, I think
- I did only mild restructuring and did not yet check for consistency everywhere

**Comment by junghans** [comment]
Ok, that is great work, I think:

- dropping the pdf is fine
- having all figure as png is fine as well as long as the keep the sources around somewhere
- once merged we can work on the reference part with @felipeZ

**Comment by marvinbernhardt** [comment]
Glad you like it :)
So for the flow diagrams I think I would put the tikz code in the fig folder, ok?

**Comment by junghans** [comment]
That is ok!

**Comment by junghans** [comment]
I am getting a couple of
```
bibliography.rst:5: WARNING: Citation [Ruehle:2008] is not referenced.
```
so I removed a couple of unused references. Then I realized the citation on old titlepage, now index.rst, are not showing. Any ideas?

Also the xml from `\lstinputlisting()` are missing as well, could code the code in there directly?

And we need to restore the source for some of the images.

**Comment by junghans** [comment]
I hopefully fixed the titlepage.

@marvinbernhardt @DRosen285 can you guys have a look at the xml files previously included with `\lstinputlisting()`?

**Comment by DRosen285** [comment]
Sorry for being late to the party. I got caught up with other stuff. I'll take a look over the Thanksgiving weekend. Thanks @marvinbernhardt  for the good work so far.

**Comment by junghans** [comment]
@DRosen285 thanks, the other thing I just saw is, that the footnote got converted in a strange way, maybe should just add them to text. Similar to what we did for the images.

In general I pretty happy with this, once merged this will make our life much easier. The reference section isn't a big deal to add later.

**Comment by DRosen285** [comment]
I have a problem with building the documentation.
During cmake I get:
-- The following REQUIRED packages have been found:

 * boost_program_options (required version == 1.71.0)
 * boost_filesystem (required version == 1.71.0)
 * boost_headers (required version == 1.71.0)
 * boost_system (required version == 1.71.0)
 * Boost (required version >= 1.53.0)

When I run make:
It complains 
./votca_property: error while loading shared libraries: libboost_program_options.so.1.62.0: cannot open shared object file: No such file or directory

Any suggestions, why it's looking for boost1.62?

**Comment by junghans** [comment]
I guess you have an previously built/installed libvotca_tools.so somewhere in your `LD_LIBRARY_PATH` (or as a system location). You could try to run `ldd votca_property` to check that. Unsetting `LD_LIBRARY_PATH` should help. If the prevouis build is installed in a system path, e.g. `/usr/local`, you will have to uninstall it first.

**Comment by DRosen285** [comment]
Thanks @junghans,that helped.

Now I've discovered issue with sphinx. I had to add the following to the config.py file

def setup(app):
    app.add_source_suffix('.md', 'markdown')
    app.add_source_parser(CommonMarkParser)
    app.add_config_value('markdown_parser_config', {
        'auto_toc_tree_section': 'Content',
        'enable_auto_doc_ref': True,
        'enable_auto_toc_tree': True,
        'enable_eval_rst': True,
        'enable_inline_math': True,
        'enable_math': True,
    }, True)

Otherwise I get:

Sphinx error:
Source parser for markdown not registered
make[3]: *** [share/doc/CMakeFiles/doc.dir/build.make:66: share/doc/CMakeFiles/doc] Error 2
make[2]: *** [CMakeFiles/Makefile2:1934: share/doc/CMakeFiles/doc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1941: share/doc/CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:788: doc] Error 2

However, I still get the following warning:
Running Sphinx v1.8.5
WARNING: extension 'recommonmark' has no setup() function; is it really a Sphinx extension module?

**Comment by junghans** [comment]
Hmm, we had that block, but dropped it to support Sphinx 2.0. Also there shouldn't be any `md` files anymore in the master version anyhow.

**Comment by junghans** [comment]
It might be from this line: https://github.com/votca/votca/blob/5407c86f6e26e5962715e893dcc1eac2faa14a44/share/doc/conf.py.in#L13

**Comment by junghans** [comment]
There are two footnotes in `theory.rst`, `[1]` and `[2]` that look strange, otherwise we are getting close.

**Comment by junghans** [comment]
After https://github.com/votca/votca/pull/523 merged things should be bit easier.

**Comment by junghans** [comment]
Thanks all, the new website is online now: https://votca.github.io/, I fixed the csg-tutorial page and the language guide as well.

**Pull request merged**
