### PR TITLE
add missing package for FreeBSD

### PR DESCRIPTION
**Pull request by junghans**
Fix https://github.com/votca/votca/issues/292

### CODE REVIEW

**Comment by junghans** [comment]
Ping @yurivict

**Comment by yurivict** [comment]
The fix will get in with the next release.

**Comment by junghans** [comment]
> The fix will get in with the next release.

Thanks, let me know if it helps.

**Comment by yurivict** [comment]
The build now fails:
```
/usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/RSpace.hpp:179:22: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
    std::array<T, 3> force_i = {0, 0, 0};
                     ^
/usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/QDMEwald.hpp:126:10: note: in instantiation of member function 'RSpace<double>::compute' requested here
  rspace.compute(xyz, q, d, Q);
         ^
/usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/dummy.cpp:72:12: note: in instantiation of member function 'QDMEwald<double>::compute' requested here
    qdme_d.compute(xyz, q, d, Q);
           ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
In file included from /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/dummy.cpp:21:
In file included from /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/QDMEwald.hpp:25:
/usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/RSpace.hpp:180:22: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
    std::array<T, 3> torque_i = {0, 0, 0};
                     ^
/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
```

**Comment by junghans** [comment]
> The build now fails:
> 
> ```
> /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/RSpace.hpp:179:22: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
>     std::array<T, 3> force_i = {0, 0, 0};
>                      ^
> /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/QDMEwald.hpp:126:10: note: in instantiation of member function 'RSpace<double>::compute' requested here
>   rspace.compute(xyz, q, d, Q);
>          ^
> /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/dummy.cpp:72:12: note: in instantiation of member function 'QDMEwald<double>::compute' requested here
>     qdme_d.compute(xyz, q, d, Q);
>            ^
> /usr/include/c++/v1/__tuple:219:64: note: template is declared here
> template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
>                                                                ^
> In file included from /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/dummy.cpp:21:
> In file included from /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/QDMEwald.hpp:25:
> /usr/ports/science/votca/work/votca-1.6/xtp/src/QDMEwald/src/RSpace.hpp:180:22: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
>     std::array<T, 3> torque_i = {0, 0, 0};
>                      ^
> /usr/include/c++/v1/__tuple:219:64: note: template is declared here
> template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
>                                                                ^
> ```

This isn't votca-xtp-1.6, but the master version, which is far from any release. This patch needs to be applied on to the v1.6 version.

**Comment by yurivict** [comment]
> This isn't votca-xtp-1.6, but the master version, which is far from any release. This patch needs to be applied on to the v1.6 version.

Ok.

**Comment by junghans** [comment]
@yurivict is this sill needed?

**Comment by yurivict** [comment]
Not sure if this bug is needed.

**Pull request merged**
